### ISSUE TITLE
Trying to get it to work with Google Auth2

### ISSUE THREAD

**Issue by PhilAndrew** [dakatsuka/akka-http-oauth2-client#1]
Problem on getAccessToken

Can you tell me what this error means?

[info] java.lang.IllegalArgumentException: requirement failed: Illegal port: -1
[info]  at scala.Predef$.require(Predef.scala:277)
[info]  at akka.http.scaladsl.model.headers.Host.<init>(headers.scala:521)
[info]  at akka.http.scaladsl.model.headers.Host$.apply(headers.scala:516)
[info]  at akka.http.scaladsl.HttpExt._outgoingConnection(Http.scala:373)
[info]  at akka.http.scaladsl.HttpExt.outgoingConnectionHttps(Http.scala:346)
[info]  at com.github.dakatsuka.akka.http.oauth2.client.Config.connection(Config.scala:25)
[info]  at com.github.dakatsuka.akka.http.oauth2.client.Client.getAccessToken(Client.scala:23)

**Comment by GRBurst** [comment]
hey @PhilAndrew ,
did you set the `code` and `redirect_uri` parameters? they are required for the request to work. ```require(params.contains("code"))
require(params.contains("redirect_uri"))```

**Comment by PhilAndrew** [comment]
I gave up and made a nodejs REST version and called that from my Scala code via REST since I knew I could rely on the nodejs libraries to work and I could understand if they didn't work. I'd like to make this work later some time.
